src/ZeeBi.UI/Controllers/AuthenticationController.cs
using System;
using System.Web;
using System.Web.Mvc;
using ZeeBi.UI.DataAccess;
using ZeeBi.UI.Models;
using ZeeBi.UI.Services;

namespace ZeeBi.UI.Controllers
{
	public class AuthenticationController : Controller
	{
		private readonly UsersRepository _usersRepository;

		public AuthenticationController()
		{
			_usersRepository = new UsersRepository();
		}

		private RedirectResult ReturnToUrl(string returnUrl)
		{
			return Redirect(returnUrl ?? "/");
		}

		public ActionResult SignOut(string returnUrl)
		{
			var cookie = new HttpCookie("userId");
			cookie.Expires = new DateTime(1970, 1, 1);
			Response.SetCookie(cookie);

			return ReturnToUrl(returnUrl);
		}

		public ActionResult Authenticate(string token, string returnUrl)
		{
			if (string.IsNullOrEmpty(token))
			{
				return ReturnWithError(returnUrl);
			}
			
			var rpx = new Rpx("87df721ebccbde5919f4258b45d8f3d0dc1db546", "https://shcil.rpxnow.com/");
			var response = rpx.AuthInfo(token);
			var parser = new RpxResponseParser(response);
			if (parser.Status != RpxReponseStatus.Ok)
			{
				return ReturnWithError(returnUrl);
			}
			else
			{
				var responseUser = parser.BuildUser();
				var user = _usersRepository.FindByOpenId(responseUser.OpenId);
				if (user == null)
				{
					user = new User {
						Email = responseUser.Email,
						Friendly = responseUser.Friendly,
						OpenId = responseUser.OpenId,
						UserName = responseUser.UserName
					};
					DB.Users.Insert(user);
				}

				Response.AppendCookie(new HttpCookie("userId", user.Id.ToString()));

				return ReturnToUrl(returnUrl);
			}
		}

		private ActionResult ReturnWithError(string returnUrl)
		{
			TempData["Message"] = "There was a problem signing you in. Verify your credentials and try again.";

			return ReturnToUrl(returnUrl);
		}
	}
}

src/ZeeBi.UI/Views/Shared/SignInLink.cshtml
@model System.String

@{ var authenticationUrl = Url.Action("Authenticate", "Authentication", new { returnUrl = Request.Url.ToString() }, "http"); }
<a class="rpxnow" onclick="return false;" href="https://shcil.rpxnow.com/openid/v2/signin?token_url=@Url.Encode(authenticationUrl)">@Model</a>

src/ZeeBi.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>@(string.IsNullOrEmpty(ViewBag.Title) ? string.Empty : ViewBag.Title + " | ")extremelylongurlshorteningserviceprovider.info</title>
	<link href="@Url.Content("~/Content/reset.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
	<link rel="shortcut icon" href="@Url.Content("~/Content/img/favicon.ico")" />

	@RenderSection("head", false)
</head>

<body>
	<div id="content">
		<div id="topbar">
			<div id="login-indicator">
				@if (CurrentUser == null)
				{
					@Html.Partial("SignInLink", "Sign In")
				}
				else
				{
					<span class="username">@CurrentUser.Friendly</span> @:| 
					<a href="@Url.Action("SignOut", "Authentication", new { returnUrl = Request.Url.ToString() })">Sign Out</a>
				}
			</div>

			@if (TempData["Message"] != null)  
			{
				<div id="global-message">
					<span class="error">@TempData["Message"]</span>
				</div>
			}		
		</div>

		<div id="header">
			<h1><a href="/">
				<img src="@Url.Content("~/Content/img/logo.png")" alt="extremelylongurlshorteningserviceprovider.info" />
			</a></h1>
		</div>

		@RenderBody()
		<div id="footer-pusher"></div>
	</div>

	<div id="footer">
		extremelylongurlshorteningserviceprovider.info is a proud member of the <a href="http://team.delver.com" target="_blank">Delver</a> Creativity Dojo 2011 <br />
		Graphic design by Isaac Studios
	</div>

<script type="text/javascript">
	var rpxJsHost = (("https:" == document.location.protocol) ? "https://" : "http://static.");
	document.write(unescape("%3Cscript src='" + rpxJsHost +
"rpxnow.com/js/lib/rpx.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
	RPXNOW.overlay = true;
	RPXNOW.language_preference = 'en';
</script>

<script type="text/javascript">

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-21723957-1']);
	_gaq.push(['_trackPageview']);

	(function () {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();

</script>

</body>

</html>