src/ZeeBi.UI/Models/Url.cs
using System;
using MongoDB.Bson;

namespace ZeeBi.UI.Models
{
	public class Url
	{
		public string Id { get; set; }

		public string LongUrl { get; set; }

		public DateTime Created { get; set; }

		public int ClickCount { get; set; }

		public ObjectId UserId { get; set; }
	}

	public class PageView
	{
		public ObjectId Id { get; set; }

		public string UrlId { get; set; }

		public DateTime ViewedAt { get; set; }

		public string UserIp { get; set; }

		public string UserAgent { get; set; }

		public string OriginalUserAgent { get; set; }
	}
}

src/ZeeBi.UI/ViewModels/Urls/HomeViewModel.cs
using System;
using System.Collections.Generic;
using ZeeBi.UI.Models;

namespace ZeeBi.UI.ViewModels.Urls
{
	public class HomeViewModel
	{
		public string LongUrl { get; set; }
		public string Id { get; set; }

		public IList<Url> MyUrls { get; set; }

		public int TotalUrlsShortened { get; set; }
	}
}

src/ZeeBi.UI/Controllers/StatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using ZeeBi.UI.DataAccess;
using ZeeBi.UI.Models;
using ZeeBi.UI.Services;
using ZeeBi.UI.ViewModels.Stats;
using ZeeBi.UI.Utils;

namespace ZeeBi.UI.Controllers
{
	public class StatsController : Controller
	{
		[HttpGet]
		public ActionResult Info(string id)
		{
			RequestsLog.SaveRequestData(HttpContext);
			var url = DB.Urls.FindOneById(id);
			if (url == null)
				return Responses.NotFound;
			
			if (Request.AcceptTypes != null && Request.AcceptTypes.Contains("application/json"))
			{
				return Json(url, JsonRequestBehavior.AllowGet);
			}

			var query = Query.EQ("UrlId", id);

			var pageViewCount = DB.PageViews.Count(query);

			return View(new StatsViewModel {
				PageViewCount = pageViewCount,
				Url = url,
				PageViewsByUserAgent = GetPageViewsByUserAgent(query),
				PageViewsByDate = GetPageViewsByDate(query)
			});
		}

		private ICollection<KeyValuePair<string, int>> GetPageViewsByUserAgent(IMongoQuery query)
		{
			var reduce = new BsonJavaScript("function(o, agg) { agg.count++; }");
			var results = DB.PageViews.Group(query, "UserAgent", new { count = 0 }.ToBsonDocument(), reduce, null).ToList();

			return results
				.ToKeyValuePairs(x => x["UserAgent"].AsString, x => x["count"].ToInt32())
				.OrderByDescending(kvp => kvp.Value)
				.ToList();
		}

		private ICollection<KeyValuePair<DateTime, int>> GetPageViewsByDate(IMongoQuery query)
		{
			var map = new BsonJavaScript(
@"function() { 
	day = Date.UTC(this.ViewedAt.getFullYear(), this.ViewedAt.getMonth(), this.ViewedAt.getDate());
	emit({day: day, daynum: this.ViewedAt.getDate()}, {count: 1});
}");

			var reduce = new BsonJavaScript(
@"function(key, values) {
	var count = 0;
	values.forEach(function(v) {
		count += v['count'];
	});
	return {count: count};
}");

			var results = DB.PageViews.MapReduce(query, map, reduce, MapReduceOptions.SetOutput(MapReduceOutput.Inline)).InlineResults.ToList();
			return results
				.ToKeyValuePairs(
					x => DateTimeFromUnixTime(x["_id"].AsBsonDocument["day"].AsDouble), 
					x => x["value"].AsBsonDocument["count"].ToInt32())
				.OrderByDescending(kvp => kvp.Key).ToList();
		}

		private DateTime DateTimeFromUnixTime(double unixTime)
		{
			return new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddMilliseconds(unixTime);
		}
	}
}

src/ZeeBi.UI/Controllers/UrlsController.cs
using System;
using System.Web.Mvc;
using MongoDB.Bson;
using ZeeBi.UI.Models;
using ZeeBi.UI.Services;
using ZeeBi.UI.ViewModels.Urls;

namespace ZeeBi.UI.Controllers
{
	public class UrlsController : Controller
	{
		private readonly UrlNormalizer _urlNormalizer;
		private readonly UrlsRepository _urlsRespository;

		public UrlsController()
		{
			// todo IOC?
			_urlNormalizer = new UrlNormalizer();
			_urlsRespository = new UrlsRepository();
		}

		public ActionResult Index()
		{
			RequestsLog.SaveRequestData(HttpContext);
			var model = new HomeViewModel();
			if (CurrentUser != null)
			{
				model.MyUrls = _urlsRespository.FindByUser(CurrentUser.Id);
			}

			model.LongUrl = TempData["Input.LongUrl"] as string;
			model.Id = TempData["Input.Id"] as string;
			model.TotalUrlsShortened = _urlsRespository.GetTotalUrlsShortened();
			return View(model);
		}

		protected User CurrentUser
		{
			get { return ViewData["currentUser"] as User; }
		}

		public ActionResult Follow(string id)
		{
			var url = _urlsRespository.FindById(id);
			if (url == null)
				return Responses.NotFound;
			
			_urlsRespository.RecordAnalytics(url, Request);

			return new RedirectResult(url.LongUrl, false);
		}

		[HttpPost]
		public ActionResult Add(string longUrl, string id)
		{
			try
			{
				if (string.IsNullOrWhiteSpace(id)) id = null;

				var userId = CurrentUser == null ? ObjectId.Empty : CurrentUser.Id;
				var url = _urlsRespository.Add(longUrl, id, userId);
				return RedirectToAction("Created", new { id = url.Id });
			}
			catch (IdAlreadyTakenException)
			{
				return new HttpStatusCodeResult(409, "ID already taken.");
			}
			catch (InvalidUrlException)
			{
				TempData["Message"] = "This seems like an invalid URL. Wanna try again?";
				TempData["Input.LongUrl"] = longUrl;
				TempData["Input.Id"] = id;
				return RedirectToAction("Index");
			}
		}

		[HttpGet]
		public ActionResult Created(string id)
		{
			var url = _urlsRespository.FindById(id);
			if (url == null)
				return Responses.NotFound;

			return View(url);
		}


		[HttpGet]
		public ActionResult IsAvailable(string id)
		{
			var available = _urlsRespository.IsAvailable(id);
			return Json(available, JsonRequestBehavior.AllowGet);
		}

		[HttpGet]
		public ActionResult IsUrlValid(string url)
		{
			var valid = _urlNormalizer.IsValid(url);
			return Json(valid, JsonRequestBehavior.AllowGet);
		}
	}

	internal class InvalidUrlException : Exception
	{
		public string LongUrl { get; set; }

		public InvalidUrlException(string longUrl)
		{
			LongUrl = longUrl;
		}

		public override string Message
		{
			get { return "The specified URL is invalid."; }
		}
	}

	public class IdAlreadyTakenException : Exception
	{
		public IdAlreadyTakenException(string id)
		{
			Id = id;
		}

		protected string Id { get; set; }

		public override string Message
		{
			get { return "The specified ID is already taken."; }
		}
	}
}

src/ZeeBi.UI/Views/Urls/Created.cshtml
@model ZeeBi.UI.Models.Url
		   
@{
    ViewBag.Title = "URL Shortened!";
}

<style>
	#short-url 
	{
		background: transparent url("/Content/img/link.png") no-repeat;
		display: inline-block;
		background-position: left bottom;
		padding: 20px 0 20px 50px;
	}
	
	#repeat-container 
	{
		display: inline-block;
		height: 60px;
		width: 160px;
		margin: 25px -60px -50px 0;
		padding: 4px 60px 80px 50px;
		background: transparent url("/Content/img/repeat-button.png") no-repeat;
	}
	
	div { margin-bottom: 5px; }
	
</style>

<h2><em>URL</em> Shortened!</h2>

<div>
	<div id="short-url-container">
		<a id="short-url" href="/@Model.Id">@Url.RouteUrl("Follow", new { id = Model.Id }, "http")</a>
		<span id="repeat-container"><a href="@Url.Action("Index")"><button id="repeat-button"></button></a></span>
	</div>
	<div id="info-container">
		Track how users follow your URL at its <a href="@Url.Action("info", "stats", new { id = Model.Id })">info page</a>. <br />
	</div>

	@if (CurrentUser == null)
	{
		<div>
			Pro tip: if you were @Html.Partial("SignInLink", "signed in") we would remember your shortened URLs for you.
		</div>
	}

</div>

src/ZeeBi.UI/Views/Urls/Index.cshtml
@model ZeeBi.UI.ViewModels.Urls.HomeViewModel

@section head {
	<link href="@Url.Content("~/Content/home.css")" rel="stylesheet" type="text/css" />
}
<h3>Already shortened <em>@Model.TotalUrlsShortened URLs</em> and counting!</h3>

<h2>Shorten a <em>URL!</em></h2>

<div id="form-container">
	<form action="@Url.Action("add", "urls")" method="post">
		<div id="textbox-container">
			<input id="longUrl" name="longUrl" type="text" title="enter a URL to shorten" value="@Model.LongUrl" autocomplete="off"/>
			<div id="longUrl-messages" class="messages">
				<span id="longUrl-invalid" class="error">I don't think that's a valid URL</span>
			</div>
		</div>
		<div id="submit-container">
			<input class="button" type="submit" name="submit" id="submit" value="" />
		</div>
		<div id="short-url-container" class="breaker">
			<label for="id">http://extremelylongurlshorteningserviceprovider.info/</label>
			<input id="id" name="id" type="text" title="we'll make something up" value="@Model.Id" autocomplete="off"/>
			<span id="id-icon"></span>
			<div id="id-messages" class="messages">
				<span id="id-too-short" class="error">we need at least 5 characters</span>
				<span id="id-duplicate" class="error">looks like this is already taken</span>
			</div>
		</div>
	</form>
	<div class="breaker"></div>
</div>

@if (Model.MyUrls != null) 
{
	<h2>My <em>URLs</em></h2>
	<div id="my-urls-container" class="box">
		@Html.Partial("UserUrls", Model.MyUrls)
	</div>
}

<script type="text/javascript" src="@Url.Content("Scripts/lib/jquery-1.5.min.js")"></script>
<script type="text/javascript" src="@Url.Content("Scripts/lib/jquery.hint.js")"></script>

<script type="text/javascript">

	$(function () {
		$('#id, #longUrl').hint();

		$('#id').bind('change keyup', function () {
			$('#id-messages span').hide();
			$('#id-icon').removeClass('error').removeClass('ok');

			if (this.value.length == 0) return;

			if (this.value.length < 5) {
				$('#id-too-short').show();
				$('#id-icon').addClass('error');
				return;
			}

			$.getJSON('@Url.Action("isAvailable")', { "id": this.value }, function (isAvailable) {
				if (isAvailable) {
					$('#id-icon').addClass('ok');
				} else {
					$('#id-duplicate').show();
					$('#id-icon').addClass('error');
				}
			});

		});

		$('#longUrl').bind('change keyup', function () {
			$('#longUrl-messages span').hide();

			if (this.value.length == 0) return;

			$.getJSON('@Url.Action("isUrlValid")', { "url": this.value }, function (valid) {
				if (!valid) {
					$('#longUrl-invalid').show();
				}
			});
		});
	});
</script>


src/ZeeBi.UI/Views/Urls/UserUrls.cshtml
@model System.Collections.Generic.IList<ZeeBi.UI.Models.Url>

@if (Model.Count == 0)
{
	<div class="summary">You haven't shortened any URLs yet. What are you waiting for?</div>
}
else
{
	<div class="summary">
		You've shortened <em>@Model.Count</em> @(Model.Count == 1 ? "URL" : "URLs"):
	</div>
	<table id="my-urls">
		<thead>
			<tr>
				<th id="short-url-header">Short URL</th>
				<th id="long-url-header">Long URL</th>
				<th id="created-header">Created</th>
				<th id-"page-views-header">Page Views</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var url in Model) {
				<tr>
					<td><a href="@Url.RouteUrl("Follow", new { id = url.Id }, "http")" title="Copy this link to share with others">@url.Id</a></td>
					<td><a href="@url.LongUrl">@url.LongUrl</a></td>
					<td>@url.Created.ToString("yyyy-MM-dd HH:mm UTC")</td>
					<td><a href="@Url.Action("Info", "Stats", new { id = @url.Id })" title="Detailed info for this URL">@url.ClickCount</a></td>
				</tr>
			}
		</tbody>
	</table>
}